Repository gardener/gardener-extension-provider-vsphere, pull requests merged in 2020-12, with the labels that each got.

#112 Worker/update credentials for all deployments
  .github/pull_request_template.md
  Dockerfile
  go.mod
  go.sum
  pkg/controller/worker/machine_controller_manager.go
  vendor/github.com/gardener/gardener/.github/pull_request_template.md
  vendor/github.com/gardener/gardener/extensions/pkg/controller/infrastructure/reconciler.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_delete.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/interface.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/reconciler.go
  vendor/github.com/gardener/gardener/hack/.ci/set_dependency_version
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/constants/types_constants.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/addons.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/botanist.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/cleanup.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/component/interfaces.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/component/types.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/constraints_check.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/containerruntime.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane/clusterautoscaler/bootstrap.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane/clusterautoscaler/cluster_autoscaler.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane/etcd/bootstrap.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane/etcd/etcd.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane/etcd/monitoring.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane/kubecontrollermanager/kube_controller_manager.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane/kubescheduler/kube_scheduler.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/dns.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/extensions/containerruntime/containerruntime.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/extensions/controlplane/controlplane.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/extensions/infrastructure/infrastructure.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/health_check.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/infrastructure.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/systemcomponents/metricsserver/metrics_server.go
  vendor/github.com/gardener/gardener/pkg/operation/common/extensions.go
  vendor/github.com/gardener/gardener/pkg/operation/common/types.go
  vendor/github.com/gardener/gardener/pkg/operation/garden/garden.go
  vendor/github.com/gardener/gardener/pkg/operation/seed/seed.go
  vendor/github.com/gardener/gardener/pkg/operation/shoot/types.go
  vendor/github.com/gardener/gardener/pkg/operation/types.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/health/health.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/patch.go
  vendor/github.com/gardener/gardener/test/framework/common.go
  vendor/github.com/gardener/gardener/test/framework/dump.go
  vendor/github.com/gardener/gardener/test/framework/shoot_utils.go
  vendor/github.com/gardener/gardener/test/framework/shootframework.go
  vendor/modules.txt
Labels: needs/ok-to-test, platform/vsphere, priority/normal, reviewed/lgtm, size/xs

#116 Add Worker and ControlPlane CRD to examples
  example/20-crd-controlplane.yaml
  example/20-crd-worker.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#115 use patched csi-driver to fix detaching volume for non-existing node
  charts/images.yaml
Labels: area/control-plane, kind/bug, needs/ok-to-test, needs/review, platform/vsphere, priority/normal, size/xs
