Repository gardener/gardener-extension-provider-vsphere, pull requests merged in 2020-07, with the labels that each got.

#59 [ci:component:github.com/gardener/machine-controller-manager-provider-vsphere:v0.5.0->v0.6.0]
  charts/images.yaml
  vendor/github.com/gardener/gardener/hack/install-requirements.sh
Labels: needs/ok-to-test

#60 [ci:component:github.com/gardener/machine-controller-manager-provider-vsphere:v0.6.0->v0.6.1]
  charts/images.yaml
Labels: needs/ok-to-test

#54 Add machineTypeOptions to CloudProfileConfig
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  charts/images.yaml
  charts/internal/machineclass/templates/machineclass.yaml
  charts/internal/machineclass/values.yaml
  hack/api-reference/api.md
  hack/update-github-templates.sh
  pkg/apis/vsphere/helper/scheme.go
  pkg/apis/vsphere/helper/scheme_test.go
  pkg/apis/vsphere/types_cloudprofile.go
  pkg/apis/vsphere/v1alpha1/types_cloudprofile.go
  pkg/apis/vsphere/v1alpha1/zz_generated.conversion.go
  pkg/apis/vsphere/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/vsphere/validation/cloudprofile.go
  pkg/apis/vsphere/validation/cloudprofile_test.go
  pkg/apis/vsphere/zz_generated.deepcopy.go
  pkg/controller/controlplane/valuesprovider_test.go
  pkg/controller/worker/machines.go
  pkg/controller/worker/machines_test.go
Labels: area/control-plane, area/performance, kind/api-change, needs/ok-to-test, platform/vmware, priority/normal

#61 [ci:component:github.com/gardener/machine-controller-manager:v0.31.0->v0.32.0]
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm

#58 clean up possible orphan load balancer objects during deleting the infrastructure
  cmd/infra-cli/main.go
  go.mod
  go.sum
  pkg/cmd/infra-cli/loadbalancer/destroy.go
  pkg/controller/infrastructure/actuator_delete.go
  pkg/controller/infrastructure/actuator_reconcile.go
  vendor/k8s.io/cloud-provider-vsphere/pkg/cloudprovider/vsphere/loadbalancer/cleanup.go
  vendor/k8s.io/cloud-provider-vsphere/pkg/cloudprovider/vsphere/loadbalancer/config/config.go
  vendor/k8s.io/cloud-provider-vsphere/pkg/cloudprovider/vsphere/loadbalancer/nsxt_broker.go
  vendor/k8s.io/cloud-provider-vsphere/pkg/cloudprovider/vsphere/nodemanager.go
  vendor/modules.txt
Labels: area/control-plane, area/robustness, kind/enhancement, needs/ok-to-test, platform/vmware, priority/normal

#66 ignore if gateway locale service has already disappeared
  pkg/vsphere/infrastructure/task/tasks.go
Labels: area/control-plane, area/robustness, kind/enhancement, needs/ok-to-test, platform/vmware, priority/normal
