Repository gardener/gardener-extension-provider-vsphere, pull requests merged in 2021-04, with the labels that each got.

#142 Fix the infrastructure-test TestDefinition
  .test-defs/infrastructure-test.yaml
  .test-defs/provider-vsphere.yaml
  README.md
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#144 updated the provider name in the machine class template
  charts/internal/machineclass/templates/machineclass.yaml
Labels: area/dev-productivity, kind/enhancement, needs/ok-to-test, platform/vsphere, reviewed/lgtm, size/xs

#145 Increase revisionHistoryLimit
  charts/gardener-extension-provider-vsphere/templates/deployment.yaml
  charts/gardener-extension-validator-vsphere/charts/runtime/templates/deployment.yaml
  charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  charts/internal/seed-controlplane/charts/csi-vsphere/templates/vsphere-csi-controller.yaml
  charts/internal/seed-controlplane/charts/vsphere-cloud-controller-manager/templates/cloud-controller-manager.yaml
  example/controller-registration.yaml
Labels: area/ops-productivity, kind/enhancement, needs/lgtm, needs/ok-to-test, needs/review, platform/vsphere, size/xs

#147 Do not require strict decoding for Shoot resource
  pkg/validator/shoot_handler.go
Labels: kind/bug, needs/ok-to-test, platform/vsphere, reviewed/lgtm, size/xs

#148 Automated cherry pick of #147: Do not require strict decoding for Shoot resource
  pkg/validator/shoot_handler.go
Labels: kind/bug, needs/ok-to-test, needs/review, platform/vsphere, size/xs
