Repository gardener/gardener-extension-provider-vsphere, pull requests merged in 2022-07, with the labels that each got.

#262 Adapt the priority according to the gardener guideline
  charts/gardener-extension-provider-vsphere/templates/_helpers.tpl
  charts/gardener-extension-provider-vsphere/templates/deployment.yaml
  charts/gardener-extension-provider-vsphere/templates/priorityclass.yaml
  charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  charts/internal/seed-controlplane/charts/csi-vsphere/templates/csi-snapshot-validation-webhook-deployment.yaml
  charts/internal/seed-controlplane/charts/csi-vsphere/templates/deployment-csi-snapshot-controller.yaml
  charts/internal/seed-controlplane/charts/csi-vsphere/templates/deployment-vsphere-csi-controller.yaml
  charts/internal/seed-controlplane/charts/vsphere-cloud-controller-manager/templates/cloud-controller-manager.yaml
  example/controller-registration.yaml
Labels: area/quality, kind/enhancement, needs/ok-to-test, needs/review, size/xs, platform/vsphere

#264 Revert failed CI build
  VERSION
  example/controller-registration.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#265 Update version to get around dead protected branches
  VERSION
  example/controller-registration.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#269 Revert priorityclass
  charts/gardener-extension-provider-vsphere/templates/_helpers.tpl
  charts/gardener-extension-provider-vsphere/templates/deployment.yaml
  charts/gardener-extension-provider-vsphere/templates/priorityclass.yaml
  charts/images.yaml
  charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  charts/internal/seed-controlplane/charts/csi-vsphere/templates/csi-snapshot-validation-webhook-deployment.yaml
  charts/internal/seed-controlplane/charts/csi-vsphere/templates/deployment-csi-snapshot-controller.yaml
  charts/internal/seed-controlplane/charts/csi-vsphere/templates/deployment-vsphere-csi-controller.yaml
  charts/internal/seed-controlplane/charts/vsphere-cloud-controller-manager/templates/cloud-controller-manager.yaml
  example/controller-registration.yaml
Labels: area/quality, kind/regression, needs/ok-to-test, needs/review, size/xs, platform/vsphere

#267 Upgrade to vsphere CSI to 2.6.0-gardener1
  charts/images.yaml
Labels: area/storage, kind/enhancement, needs/ok-to-test, needs/review, size/xs, platform/vsphere

#271 Fix version
  charts/images.yaml
  charts/internal/seed-controlplane/charts/csi-vsphere/templates/deployment-vsphere-csi-controller.yaml
  charts/internal/shoot-system-components/charts/csi-vsphere/templates/daemonset.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs, platform/vsphere

#266 CI traits to create version upgrade PRs
  .ci/pipeline_definitions
Labels: area/dev-productivity, kind/enhancement, needs/ok-to-test, needs/review, size/xs, platform/vsphere

#273 added missing fields to vsphere secret
  docs/usage-as-end-user.md
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#274 Change `create-upgrade-prs` cron job from `5m` to '4h'
  .ci/pipeline_definitions
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#275 CI cleanups
  .ci/pipeline_definitions
Labels: needs/ok-to-test, needs/review, size/s, ci/broken-pipeline-definition

#276 Fix indentation on inheritance
  .ci/pipeline_definitions
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#277 Upgrade the vsphere CCM
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#278 Remove install-requirement and use tools.mk
  Makefile
Labels: area/dev-productivity, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, platform/vsphere

#268 Adds MaxAllowed for VPA objects
  charts/internal/machine-controller-manager/seed/templates/vpa.yaml
  charts/internal/seed-controlplane/charts/csi-vsphere/templates/csi-snapshot-validation-webhook-vpa.yaml
  charts/internal/seed-controlplane/charts/csi-vsphere/templates/vpa-csi-snapshot-controller.yaml
  charts/internal/seed-controlplane/charts/csi-vsphere/templates/vpa-vsphere-csi-controller.yaml
  charts/internal/seed-controlplane/charts/vsphere-cloud-controller-manager/templates/vpa.yaml
Labels: kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s, area/auto-scaling, platform/vsphere

#279 Upgrade dependencies to latest
  charts/images.yaml
Labels: needs/ok-to-test, needs/review, size/s

#282 More changes, thanks Nick!
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#281 Add credential docs
  docs/prepare-vsphere.md
  docs/usage-as-operator.md
Labels: area/documentation, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/m, platform/vsphere

#283 fix os version paths and naming
  docs/prepare-vsphere.md
  docs/usage-as-operator.md
Labels: area/documentation, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, platform/vsphere

#284 update chart image for vsphere-cloud-controller-manager
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#285 Update readme
  README.md
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#286 add note about Storage Policy Provisioning for etcd-main storage class
  docs/prepare-vsphere.md
Labels: area/documentation, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s, platform/vsphere
