Repository gardener/gardener-extension-provider-vsphere, pull requests merged in 2022-11, with the labels that each got.

#315 Finish GCVE automation
  .ci/pipeline_definitions
  .ci/terraform/.terraform.lock.hcl
  .ci/terraform/local-values.yaml
  .ci/terraform/main.tf
  .ci/terraform/shell.tftpl
  .ci/terraform/variables.tf
  .ci/test-integration
  .gitignore
Labels: area/dev-productivity, kind/test, needs/ok-to-test, reviewed/lgtm, size/m, platform/vsphere, merge/squash

#316 Update API Core version in examples to core.gardener.cloud/v1beta1
  README.md
  docs/usage-as-end-user.md
  docs/usage-as-operator.md
Labels: area/usability, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, platform/vsphere

#317 Cleanup build pipelines
  .ci/pipeline_definitions
  .ci/terraform/main.tf
Labels: area/ops-productivity, kind/test, needs/ok-to-test, reviewed/lgtm, size/s, platform/vsphere, merge/squash

#318 Cleanup scheduler.alpha.kubernetes.io/critical-pod annotations
  charts/internal/machine-controller-manager/seed/templates/deployment.yaml
Labels: area/open-source, kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/xs, platform/vsphere

#320 Release rollup
  .ci/pipeline_definitions
  .test-defs/infrastructure-test.yaml
  Dockerfile
  go.mod
  go.sum
  vendor/github.com/gardener/etcd-druid/api/v1alpha1/etcd_types.go
  vendor/github.com/gardener/etcd-druid/api/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/huandu/xstrings/.travis.yml
  vendor/github.com/huandu/xstrings/README.md
  vendor/github.com/huandu/xstrings/convert.go
  vendor/github.com/prometheus/client_golang/prometheus/counter.go
  vendor/github.com/prometheus/client_golang/prometheus/histogram.go
  vendor/github.com/prometheus/client_golang/prometheus/metric.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/istio.io/api/networking/v1alpha3/envoy_filter.gen.json
  vendor/istio.io/api/networking/v1alpha3/envoy_filter.pb.go
  vendor/istio.io/api/networking/v1alpha3/envoy_filter.proto
  vendor/istio.io/api/networking/v1alpha3/virtual_service.pb.go
  vendor/istio.io/api/networking/v1alpha3/virtual_service.proto
  vendor/istio.io/api/networking/v1beta1/virtual_service.pb.go
  vendor/istio.io/api/networking/v1beta1/virtual_service.proto
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go
Labels: needs/ok-to-test, reviewed/lgtm, size/s, platform/vsphere, merge/squash
