Repository gardener/gardener-extension-provider-vsphere, pull requests merged in 2022-01, with the labels that each got.

#193 `make generate` for the year change
  pkg/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/apis/vsphere/v1alpha1/zz_generated.conversion.go
  pkg/apis/vsphere/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/vsphere/v1alpha1/zz_generated.defaults.go
  pkg/apis/vsphere/zz_generated.deepcopy.go
Labels: needs/ok-to-test

#194 Make leader election resource lock configurable and default to leases
  charts/gardener-extension-provider-vsphere/templates/deployment.yaml
  charts/gardener-extension-provider-vsphere/values.yaml
  cmd/gardener-extension-provider-vsphere/app/app.go
  example/controller-registration.yaml
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, platform/vsphere

#196 Add check for the docforge manifest
  .ci/verify
  .gitignore
  Makefile
  hack/tools/bin/.gitkeep
Labels: area/documentation, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, platform/vsphere

#199 Fixed broken links 01.2022
  docs/usage-as-operator.md
Labels: area/documentation, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#198 Update RBAC for leader election of `machine-controller-manager`
  charts/internal/machine-controller-manager/seed/templates/clusterrole.yaml
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, needs/review, size/xs, platform/vsphere

#202 Kubernetes Version Configurability per Worker Pool
  docs/usage-as-end-user.md
  pkg/webhook/controlplane/ensurer.go
Labels: area/usability, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, platform/vsphere, merge/squash

#201 Support for Kubernetes v1.23
  README.md
  pkg/webhook/controlplane/ensurer.go
Labels: area/open-source, area/usability, exp/intermediate, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, topology/garden, topology/seed, topology/shoot, platform/vsphere

#197 Updated vsphere-csi-driver to 2.4.1
  charts/images.yaml
  charts/internal/seed-controlplane/charts/csi-vsphere/templates/deployment-vsphere-csi-controller.yaml
  charts/internal/seed-controlplane/charts/csi-vsphere/templates/service-vsphere-csi-controller.yaml
  charts/internal/shoot-system-components/charts/csi-vsphere/templates/_helpers.tpl
  charts/internal/shoot-system-components/charts/csi-vsphere/templates/configmap-internal-featurestate.yaml
  charts/internal/shoot-system-components/charts/csi-vsphere/templates/daemonset.yaml
  pkg/controller/controlplane/valuesprovider.go
Labels: area/control-plane, kind/task, needs/ok-to-test, reviewed/lgtm, size/s, platform/vsphere

#192 🛡 Enable `ServiceAccount` token projection and token requestor
  Makefile
  charts/gardener-extension-provider-vsphere/templates/deployment.yaml
  charts/gardener-extension-provider-vsphere/templates/serviceaccount.yaml
  charts/gardener-extension-provider-vsphere/values.yaml
  charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  charts/internal/machine-controller-manager/seed/templates/serviceaccount.yaml
  charts/internal/machine-controller-manager/seed/values.yaml
  charts/internal/machine-controller-manager/shoot/templates/clusterrolebinding-machine-controller-manager.yaml
  charts/internal/machine-controller-manager/shoot/templates/rolebinding-machine-controller-manager.yaml
  charts/internal/machine-controller-manager/shoot/values.yaml
  charts/internal/seed-controlplane/charts/csi-vsphere/templates/deployment-csi-snapshot-controller.yaml
  charts/internal/seed-controlplane/charts/csi-vsphere/templates/deployment-vsphere-csi-controller.yaml
  charts/internal/seed-controlplane/charts/vsphere-cloud-controller-manager/templates/cloud-controller-manager.yaml
  charts/internal/seed-controlplane/charts/vsphere-cloud-controller-manager/templates/configmap-observability.yaml
  charts/internal/seed-controlplane/values.yaml
  charts/internal/shoot-system-components/charts/csi-vsphere/templates/clusterrole-csi-driver.yaml
  charts/internal/shoot-system-components/charts/csi-vsphere/templates/clusterrole-csi-syncer.yaml
  charts/internal/shoot-system-components/charts/csi-vsphere/templates/clusterrolebinding-csi-attacher.yaml
  charts/internal/shoot-system-components/charts/csi-vsphere/templates/clusterrolebinding-csi-driver.yaml
  charts/internal/shoot-system-components/charts/csi-vsphere/templates/clusterrolebinding-csi-provisioner.yaml
  charts/internal/shoot-system-components/charts/csi-vsphere/templates/clusterrolebinding-csi-resizer.yaml
  charts/internal/shoot-system-components/charts/csi-vsphere/templates/clusterrolebinding-csi-snapshot-controller.yaml
  charts/internal/shoot-system-components/charts/csi-vsphere/templates/clusterrolebinding-csi-snapshotter.yaml
  charts/internal/shoot-system-components/charts/csi-vsphere/templates/clusterrolebinding-csi-syncer.yaml
  charts/internal/shoot-system-components/charts/csi-vsphere/templates/daemonset.yaml
  charts/internal/shoot-system-components/charts/csi-vsphere/templates/role-csi-syncer.yaml
  charts/internal/shoot-system-components/charts/csi-vsphere/templates/rolebinding-csi-attacher.yaml
  charts/internal/shoot-system-components/charts/csi-vsphere/templates/rolebinding-csi-provisioner.yaml
  charts/internal/shoot-system-components/charts/csi-vsphere/templates/rolebinding-csi-resizer.yaml
  charts/internal/shoot-system-components/charts/csi-vsphere/templates/rolebinding-csi-snapshot-controller.yaml
  charts/internal/shoot-system-components/charts/csi-vsphere/templates/rolebinding-csi-snapshotter.yaml
  charts/internal/shoot-system-components/charts/csi-vsphere/templates/rolebinding-csi-syncer.yaml
  charts/internal/shoot-system-components/charts/csi-vsphere/templates/serviceaccount.yaml
  charts/internal/shoot-system-components/charts/vsphere-cloud-controller-manager/templates/rbac-cloud-controller-manager.yaml
  cmd/gardener-extension-provider-vsphere/app/app.go
  example/controller-registration.yaml
  go.mod
  go.sum
  pkg/controller/controlplane/add.go
  pkg/controller/controlplane/valuesprovider.go
  pkg/controller/controlplane/valuesprovider_test.go
  pkg/controller/worker/actuator.go
  pkg/controller/worker/add.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/controlplane/genericactuator/actuator.go
  vendor/github.com/huandu/xstrings/.travis.yml
  vendor/github.com/huandu/xstrings/README.md
  vendor/github.com/huandu/xstrings/common.go
  vendor/github.com/huandu/xstrings/convert.go
  vendor/github.com/huandu/xstrings/format.go
  vendor/github.com/huandu/xstrings/go.mod
  vendor/github.com/huandu/xstrings/manipulate.go
  vendor/github.com/huandu/xstrings/stringbuilder.go
  vendor/github.com/huandu/xstrings/stringbuilder_go110.go
  vendor/github.com/huandu/xstrings/translate.go
  vendor/modules.txt
Labels: area/security, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xl, merge/squash
