Repository gardener/gardener-extension-provider-vsphere, pull requests merged in 2022-02, with the labels that each got.

#207 Updated vsphere-csi-driver images
  charts/images.yaml
Labels: area/control-plane, kind/technical-debt, needs/ok-to-test, needs/review, size/xs, platform/vsphere

#205 Add support for sa token volume projection in validator charts
  charts/gardener-extension-validator-vsphere/charts/application/templates/rbac.yaml
  charts/gardener-extension-validator-vsphere/charts/application/templates/serviceaccount.yaml
  charts/gardener-extension-validator-vsphere/charts/runtime/templates/deployment.yaml
  charts/gardener-extension-validator-vsphere/charts/runtime/templates/serviceaccount.yaml
  charts/gardener-extension-validator-vsphere/values.yaml
  docs/deployment.md
Labels: area/security, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/m, platform/vsphere

#208 Vendor gardener/gardener@v1.39.4
  example/20-crd-extensions.gardener.cloud_bastions.yaml
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_restore.go
  vendor/github.com/gardener/gardener/pkg/apis/core/helper/helpers.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/helper.go
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types_bastion.go
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config.go
  vendor/github.com/huandu/xstrings/.travis.yml
  vendor/github.com/huandu/xstrings/README.md
  vendor/github.com/huandu/xstrings/common.go
  vendor/github.com/huandu/xstrings/convert.go
  vendor/github.com/huandu/xstrings/format.go
  vendor/github.com/huandu/xstrings/go.mod
  vendor/github.com/huandu/xstrings/manipulate.go
  vendor/github.com/huandu/xstrings/stringbuilder.go
  vendor/github.com/huandu/xstrings/stringbuilder_go110.go
  vendor/github.com/huandu/xstrings/translate.go
  vendor/modules.txt
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/m, platform/vsphere

#212 Keep `cloud-controller-manager`'s `ClusterRoleBinding` on deletion
  charts/internal/shoot-system-components/charts/vsphere-cloud-controller-manager/templates/rbac-cloud-controller-manager.yaml
Labels: area/usability, kind/bug, needs/ok-to-test, needs/review, size/xs, platform/vsphere

#213 Master
  charts/internal/shoot-system-components/charts/vsphere-cloud-controller-manager/templates/rbac-cloud-controller-manager.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#214 Fix CI Build status link
  README.md
Labels: area/documentation, kind/task, needs/ok-to-test, reviewed/lgtm, size/xs, platform/vsphere
