Repository gardener/gardener-extension-provider-vsphere, pull requests merged in 2022-03, with the labels that each got.

#216 Add object selector for provider type in the `gardener-extensions-validator-vsphere` webhook
  charts/gardener-extension-validator-vsphere/charts/application/templates/validatingwebhook-validator.yaml
  charts/gardener-extension-validator-vsphere/values.yaml
  example/40-validatingwebhookconfiguration.yaml
Labels: area/robustness, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, platform/vsphere

#219 Remove TODO for kubelet's `--cloud-provider` flag
  pkg/webhook/controlplane/ensurer.go
Labels: area/usability, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs, platform/vsphere

#211 Fix serviceaccount defaulting during helm upgrade
  charts/gardener-extension-validator-vsphere/charts/runtime/templates/deployment.yaml
Labels: needs/ok-to-test, needs/review
