Repository gardener/gardener-extension-provider-vsphere, pull requests merged in 2023-07, with the labels that each got.

#444 Introduce persona-based docs
  .docforge/manifest.yaml
  docs/development/local-setup.md
  docs/operations/deployment.md
  docs/operations/operations.md
  docs/usage/prepare-vsphere.md
  docs/usage/tanzu-vsphere.md
  docs/usage/usage.md
Labels: kind/cleanup, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#446 Copy 98cd8533, removed sfz forbidding validation (gardener/gardener-extension-provider-gcp#433)
  pkg/apis/vsphere/validation/shoot.go
  pkg/apis/vsphere/validation/shoot_test.go
Labels: area/control-plane, kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/xs, area/auto-scaling, platform/vsphere

#450 Fix scale-from-zero issues
  README.md
  charts/internal/machineclass/templates/machineclass.yaml
  charts/internal/machineclass/values.yaml
  pkg/controller/worker/machines.go
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm
