Repository gardener/gardener-extension-provider-vsphere, pull requests merged in 2023-01, with the labels that each got.

#353 Drop support for kubernetes < 1.20 for vSphere extension provider
  charts/gardener-extension-provider-vsphere/templates/poddisruptionbudget.yaml
  charts/internal/seed-controlplane/charts/vsphere-cloud-controller-manager/values.yaml
  charts/internal/shoot-crds/charts/volumesnapshots/templates/crd-volumesnapshotclasses.yaml
  charts/internal/shoot-crds/charts/volumesnapshots/templates/crd-volumesnapshotcontents.yaml
  charts/internal/shoot-crds/charts/volumesnapshots/templates/crd-volumesnapshots.yaml
  charts/internal/shoot-crds/charts/volumesnapshots/values.yaml
  charts/internal/shoot-system-components/charts/csi-vsphere/templates/_helpers.tpl
  charts/internal/shoot-system-components/charts/csi-vsphere/templates/daemonset.yaml
  charts/internal/shoot-system-components/charts/csi-vsphere/values.yaml
  docs/tanzu-vsphere.md
  docs/usage-as-operator.md
  example/controller-registration.yaml
  hack/api-reference/api.json
  hack/api-reference/config.json
  pkg/apis/vsphere/validation/controlplane_test.go
  pkg/controller/controlplane/valuesprovider.go
  pkg/controller/controlplane/valuesprovider_test.go
Labels: area/open-source, kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/xl, platform/vsphere, merge/squash

#354 Fix generate scripts
  charts/images.yaml
  example/20-crd-druid.gardener.cloud_etcds.yaml
  example/20-crd-extensions.gardener.cloud_backupbuckets.yaml
  example/20-crd-extensions.gardener.cloud_backupentries.yaml
  example/20-crd-extensions.gardener.cloud_bastions.yaml
  example/20-crd-extensions.gardener.cloud_containerruntimes.yaml
  example/20-crd-extensions.gardener.cloud_controlplanes.yaml
  example/20-crd-extensions.gardener.cloud_dnsrecords.yaml
  example/20-crd-extensions.gardener.cloud_extensions.yaml
  example/20-crd-extensions.gardener.cloud_infrastructures.yaml
  example/20-crd-extensions.gardener.cloud_networks.yaml
  example/20-crd-extensions.gardener.cloud_operatingsystemconfigs.yaml
  example/20-crd-extensions.gardener.cloud_workers.yaml
  example/doc.go
Labels: area/dev-productivity, kind/cleanup, needs/ok-to-test, needs/review, size/m, platform/vsphere

#359 Enable cleanup of image snapshots
  .ci/pipeline_definitions
Labels: area/cost, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, platform/vsphere

#360 Add Fluent Operator resources
  charts/gardener-extension-provider-vsphere/templates/clusterfilters-logging.yaml
  example/controller-registration.yaml
Labels: area/logging, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s, platform/vsphere

#362 Add CVE runtime context for `MCM` and `mcm-provider-vsphere`
  charts/images.yaml
Labels: area/security, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, platform/vsphere

#361 Support for Kubernetes v1.26
  README.md
Labels: area/open-source, area/usability, exp/intermediate, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, topology/garden, topology/seed, topology/shoot, platform/vsphere, merge/squash

#369 Fix volume fsType handling for CSI volumes
  charts/internal/seed-controlplane/charts/csi-vsphere/templates/deployment-vsphere-csi-controller.yaml
Labels: area/storage, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs, platform/vsphere, area/testing

#367 Adopt node CIDR immutable check
  pkg/apis/vsphere/validation/shoot.go
  pkg/apis/vsphere/validation/shoot_test.go
  pkg/validator/shoot_validator.go
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s, platform/vsphere

#370 Update g/g pull location to upstream release
  Makefile
Labels: area/dev-productivity, kind/cleanup, needs/ok-to-test, needs/review, size/xs, platform/vsphere
